// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_ThreePointUsingSPLITT__TraversalTaskAbcPOUMM();
RcppExport SEXP _rcpp_module_boot_ThreePointUsingSPLITT__TraversalTaskThreePointPMM();
RcppExport SEXP _rcpp_module_boot_ThreePointUsingSPLITT__TraversalTaskThreePointPOUMM();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_ThreePointUsingSPLITT__TraversalTaskAbcPOUMM", (DL_FUNC) &_rcpp_module_boot_ThreePointUsingSPLITT__TraversalTaskAbcPOUMM, 0},
    {"_rcpp_module_boot_ThreePointUsingSPLITT__TraversalTaskThreePointPMM", (DL_FUNC) &_rcpp_module_boot_ThreePointUsingSPLITT__TraversalTaskThreePointPMM, 0},
    {"_rcpp_module_boot_ThreePointUsingSPLITT__TraversalTaskThreePointPOUMM", (DL_FUNC) &_rcpp_module_boot_ThreePointUsingSPLITT__TraversalTaskThreePointPOUMM, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ThreePointUsingSPLITT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
